const $=s=>document.querySelector(s),API='https://data.brreg.no/enhetsregisteret/api/enheter';
const noise=/\b(holding|hjemmel|eiendom|invest|investment|property|prosjekt|utvikling)\b/i;
const customer=/bygg|snekker|tømrer|maler|gulv|vvs|rør|elektr|klinikk|helse|omsorg|studio|design|frisør|salong|restaurant|cafe|kafé|renhold|transport|service|konsulent|rådgiv|butikk|media|foto|trening/i;
function clean(s){return s.toLowerCase().normalize('NFD').replaceAll('ø','o').replaceAll('æ','ae').replaceAll('å','a').replace(/[^a-z0-9 ]/g,' ').replace(/\b(as|enk|nuf|asa|da|ans|sa)\b/g,' ').replace(/\s+/g,' ').trim()}
function suggestions(name){let w=clean(name).split(' ').filter(Boolean),out=[];if(!w.length)return[];out.push(w.join(''));if(w.length>1){out.push(w.join('-'));out.push(w.slice(0,2).join(''))}return[...new Set(out)].filter(x=>x.length>=3&&x.length<=63).slice(0,3).map(x=>x+'.no')}
function esc(s=''){return String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]))}
function score(e){let t=(e.navn+' '+(e.naeringskode1?.beskrivelse||''));let n=50;if(customer.test(t))n+=25;if(noise.test(e.navn))n-=40;if(/\b(AS|ENK)\b/.test(e.navn))n+=5;return Math.max(5,Math.min(95,n))}
function label(n){return n>=75?'Høy':n>=50?'Middels':'Lav'}
async function search(){let st=$('#status'),box=$('#results');st.textContent='Henter fra Brønnøysund…';box.innerHTML='';try{let p=new URLSearchParams({size:$('#size').value,sort:'stiftelsesdato,DESC'}),name=$('#q').value.trim(),ind=$('#industry').value;if(name)p.set('navn',name);if(ind)p.set('naeringskode',ind);let r=await fetch(API+'?'+p);if(!r.ok)throw Error('HTTP '+r.status);let j=await r.json(),a=j._embedded?.enheter||[];if($('#hideNoise').checked)a=a.filter(e=>!noise.test(e.navn));a.sort((x,y)=>score(y)-score(x));st.textContent='Fant '+(j.page?.totalElements??a.length)+' treff. Viser '+a.length+' etter filtrering.';box.innerHTML=a.map(e=>{let s=score(e),place=e.forretningsadresse?.poststed||e.postadresse?.poststed||'',d=suggestions(e.navn);return '<article class="card"><div class="top"><div><div class="name">'+esc(e.navn)+'</div><div class="meta">Org.nr. '+esc(e.organisasjonsnummer)+' · '+esc(place)+' · '+esc(e.naeringskode1?.kode||'')+' '+esc(e.naeringskode1?.beskrivelse||'')+'</div></div><span class="score s'+label(s)+'">'+label(s)+' nettbehov</span></div><div class="domains">'+d.map(x=>'<span class="domain">'+esc(x)+'</span>').join('')+'</div></article>'}).join('')||'<p>Ingen treff med disse filtrene.</p>'}catch(e){st.textContent='Kunne ikke hente data: '+e.message}}
$('#search').onclick=search;$('#q').onkeydown=e=>{if(e.key==='Enter')search()};search();